orbs:
  maven: circleci/maven@1.1.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test
          


working_directory: /tmp

jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      
    environment:
          # Customize the JVM maximum heap limit
          MAVEN_OPTS: -Xmx3200m
          
    steps:
      - checkout
      - run: java --version
      - run: mvn dependency:go-offline
      - run: mvn clean test
      - save_cache:
          key: Dummycircleci-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - test_results_path: ~/test-output/Report/test
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results \;
          when: always
          
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
