orbs:
  maven: circleci/maven@1.1.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test
          


working_directory: /tmp

jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      
    environment:
          # Customize the JVM maximum heap limit
          MAVEN_OPTS: -Xmx3200m
          
    steps:
      - checkout
      - run: java --version
      - run: mvn dependency:go-offline
      - run: mvn clean test
      - save_cache:
          key: Dummycircleci-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - test_results_path: ~/test-output/Report/test
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
