orbs:
  maven: circleci/maven@1.2.0
  
version: 2.1


workflows:
  test:
    jobs:
      - maven/test
          



jobs:
  mave/test:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - run: java --version
      - run:
            name: Install Dependencies
            command: >-
              << parameters.mvn_path >> dependency:go-offline <<#
              parameters.settings_file >> --settings << parameters.settings_file
              >><</ parameters.settings_file >>
      - run: mvn clean test
