orbs:
  maven: circleci/maven@1.1.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: alpha
          



jobs:
  maven/test:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - run: java --version
      - run:
          command: |
            mvn clean test
            PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
            cd it/
            find . -type f -exec sed -i 's/0.35-SNAPSHOT/'"$PROJECT_VERSION"'/g' {} +
            mvn clean install
      - save_cache:
          key: dmp-{{ checksum "pom.xml" }}
          paths:
          - ~/.m2
